// Interface for a generic on-chain verifier (PLONK/other)
// The concrete verifier generated by snarkjs should implement this interface.

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

interface IVerifier {
    /// @notice Verify a proof on-chain
    /// @param proof Serialized proof bytes as produced by the prover/verifier library
    /// @param pubSignals Public signals (as uint256 array) that the verifier expects
    /// @return valid True if the proof verifies
    function verify(
        bytes calldata proof,
        uint256[] calldata pubSignals
    ) external view returns (bool valid);
}
